import React from "react";
import { Route, Routes, Navigate } from "react-router-dom";

export const RoutesComponent = ({
    MainComponents,
    MessagePanel,
    Assets,
    Languages,
    Localization,
    useLanguage,
    NetworkStatus,
    getIconNameWithTheme,
    DarkMode,
    useDarkMode,
    GetLogo,
    Posts,
}) => {
    const { Profile, Feed, Messenger, Friends, Groups, Settings } =
        MainComponents;

    return (
        <>
            <Routes>
                <Route path="*" element={<Navigate to="/feed" />} />
                <Route path="/" element={<Navigate to="/feed" />} />
                <Route
                    path="/feed"
                    element={
                        <Feed
                            Assets={Assets}
                            Languages={Languages}
                            Localization={Localization}
                            useLanguage={useLanguage}
                            NetworkStatus={NetworkStatus}
                            getIconNameWithTheme={getIconNameWithTheme}
                            DarkMode={DarkMode}
                            useDarkMode={useDarkMode}
                            GetLogo={GetLogo}
                            Posts={Posts}
                        />
                    }
                />
                <Route
                    path="/profile"
                    element={
                        <Profile
                            Assets={Assets}
                            Languages={Languages}
                            Localization={Localization}
                            useLanguage={useLanguage}
                            NetworkStatus={NetworkStatus}
                            getIconNameWithTheme={getIconNameWithTheme}
                            DarkMode={DarkMode}
                            useDarkMode={useDarkMode}
                            GetLogo={GetLogo}
                            Posts={Posts}
                        />
                    }
                />
                <Route
                    path="/messenger"
                    element={
                        <Messenger
                            Assets={Assets}
                            Languages={Languages}
                            Localization={Localization}
                            useLanguage={useLanguage}
                            NetworkStatus={NetworkStatus}
                            getIconNameWithTheme={getIconNameWithTheme}
                            DarkMode={DarkMode}
                            useDarkMode={useDarkMode}
                            GetLogo={GetLogo}
                            Posts={Posts}
                        />
                    }
                />
                <Route
                    path="/messenger/:username"
                    element={
                        <MessagePanel
                            Assets={Assets}
                            Languages={Languages}
                            Localization={Localization}
                            useLanguage={useLanguage}
                            NetworkStatus={NetworkStatus}
                        />
                    }
                />
                <Route
                    path="/friends"
                    element={
                        <Friends
                            Assets={Assets}
                            Languages={Languages}
                            Localization={Localization}
                            useLanguage={useLanguage}
                        />
                    }
                />
                <Route
                    path="/friends/:username"
                    element={
                        <Friends
                            Assets={Assets}
                            Languages={Languages}
                            Localization={Localization}
                            useLanguage={useLanguage}
                        />
                    }
                />
                <Route
                    path="/groups"
                    element={
                        <Groups
                            Assets={Assets}
                            Languages={Languages}
                            Localization={Localization}
                            useLanguage={useLanguage}
                        />
                    }
                />
                <Route
                    path="/settings"
                    element={
                        <Settings
                            Assets={Assets}
                            Languages={Languages}
                            Localization={Localization}
                            useLanguage={useLanguage}
                        />
                    }
                />
            </Routes>
        </>
    );
};
